# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a363e7983c2353c9768e53b8bcb2e0e423927d6d49005b82fd97e546fa00fb22ccc6655294c42a33b9371b13544da6b21a8e60b510bc1766ad985c3793c3a3f4

test:
  secret_key_base: 302bfd00fcd9cfbc4b08484bc507bcfdc39e18d3b6ea4e3635751837195bd9e147a56637f7941f5894718ed678f4c68f6b1bb9ffbcb97400847ffd41e73ffb68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
